# Use an official Node.js runtime as the base image
FROM node:latest

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the application dependencies
RUN npm install


# Copy the rest of the application code to the container
COPY . .

# Expose the port that the application will run on (usually 80 for HTTP)
EXPOSE 3000

# Command to start the application
CMD ["npm", "start"]
